import importlib.util
import re
import tomllib
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class FrontendContractTests(unittest.TestCase):
    def test_packaged_app_uses_in_app_confirmation_dialogs(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        self.assertIn("function confirmWorkbench(", source)
        self.assertNotIn("window.confirm(", source)
        self.assertIn('id="confirmationDialog"', markup)

    def test_disabled_buttons_have_shared_explanations(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        setup = (ROOT / "desktop" / "src" / "index.html").read_text(encoding="utf-8")
        self.assertIn("function setButtonAvailability(", source)
        self.assertIn("function installDisabledButtonGuidance(", source)
        self.assertIn("dataset.disabledReason", source)
        self.assertIn("button:disabled", source)
        self.assertIn(".disabled-button-tooltip", styles)
        self.assertIn("function setButtonAvailability(", setup)
        self.assertIn("disabled-button-tooltip", setup)

    def test_create_defaults_to_setup_and_develop_preloads_the_region_map(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        develop_index = markup.index('data-create-subpage="createDevelop"')
        setup_index = markup.index('data-create-subpage="createSetup"')
        self.assertLess(develop_index, setup_index)
        self.assertIn('id="regionPackage"', markup)
        self.assertIn('id="regionSourceLibrary"', markup)
        self.assertIn('id="regionDefinition"', markup)
        self.assertIn('id="regionOutputOptions"', markup)
        self.assertIn("Output options", markup)
        self.assertIn('id="installRegionPackage"', markup)
        self.assertIn("No regional data package installed", markup)
        self.assertNotIn('id="regionAzones"', markup)
        self.assertNotIn('id="regionBzones"', markup)
        self.assertIn('id="previewRegionBuild"', markup)
        self.assertIn('id="viewRegionMap"', markup)
        self.assertIn('id="buildRegionAssets"', markup)
        self.assertIn('id="regionMapDialog"', markup)
        self.assertIn("/api/region-builder/reference", source)
        self.assertIn("/api/region-builder/packages", (ROOT / "backend" / "workbench" / "server.py").read_text(encoding="utf-8"))
        self.assertIn("/api/region-builder/sources", source)
        self.assertIn("/api/region-builder/regions", source)
        self.assertIn("/api/region-builder/preview", source)
        self.assertIn("/api/region-builder/build", source)
        self.assertIn("/api/region-builder/map", source)
        self.assertIn("/api/region-builder/map/statewide", source)
        self.assertIn("/api/region-builder/geography-options", source)
        self.assertIn('id="regionGeographyDialog"', markup)
        self.assertIn('id="regionMapRegion"', markup)
        for control in ("zoomOutRegionMap", "zoomInRegionMap", "fitRegionMap", "resetRegionMap"):
            self.assertIn(f'id="{control}"', markup)
        for layer in ("mpos", "azones", "all-bzones", "selected-bzones", "included-boundary"):
            self.assertIn(f'data-region-map-layer="{layer}"', markup)
        for label in (
            "All MPO boundaries", "All Azones", "All Bzones", "Selected MPO Bzones",
            "Selected MPO boundary overlaps",
        ):
            self.assertIn(label, markup)
        self.assertIn("at least 1% but less than 99%", markup)
        self.assertIn("Included (substantially inside)", source)
        self.assertNotIn("inside or centered", source)
        self.assertNotIn('data-region-map-layer="excluded-boundary"', markup)
        self.assertNotIn("intersecting exclusions", source)
        self.assertIn('id="regionMapNameLabels" type="checkbox" checked', markup)
        self.assertIn('id="regionMapIdLabels" type="checkbox"> Zone ID labels', markup)
        self.assertIn('id="regionMapInspector"', markup)
        self.assertIn('id="closeRegionMapInspector"', markup)
        self.assertIn('group.style.display = input.checked ? "" : "none"', source)
        self.assertNotIn("group.hidden = !input.checked", source)
        self.assertIn('aria-hidden="true" data-map-group="all-bzones"', source)
        self.assertIn("state.regionMapSelectedRegionId = regionId", source)
        self.assertIn("regionMapClientPoint", source)
        self.assertIn("regionMapHitFeature", source)
        self.assertIn("updateRegionMapIdLabels", source)
        self.assertIn("labels.length >= (useBzones ? 45 : 90)", source)
        self.assertIn("zoom >= 40", source)
        self.assertIn("zoom >= 1.75", source)
        self.assertIn("regionMapOccupyLabel", source)
        self.assertIn("bzoneMemberships", source)
        self.assertNotIn("Intersects but excluded from", source)
        self.assertIn("Included in MPOs", source)
        self.assertIn("Explored MPO official ID", source)
        self.assertIn("regionMapFeaturesView(reviewFeatures", source)
        self.assertNotIn('state.regionBuilderRegionId = $("regionMapRegion").value', source)
        self.assertIn("may extend well beyond an official MPO study area", markup)
        self.assertIn("Data sources", source)
        self.assertIn('switchCreateSubpage("createSetup", false)', source)
        self.assertIn("preloadRegionMapGeometry", source)
        self.assertIn('regionMapLoadState: "idle"', source)
        for status in ("Preparing map", "Map ready", "Cached locally"):
            self.assertIn(status, source)

    def test_editor_shows_loaded_rows_before_location_selection(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        self.assertIn(
            'if ($("editorLocationField").value === "all" || !selected.length) return true;',
            source,
        )
        self.assertIn(
            'if ($("editorLocationField").value !== "all" && !state.editorSelectedLocations.size)',
            source,
        )

    def test_editor_filter_controls_have_equal_widths(self):
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        self.assertIn("grid-template-columns: repeat(10, minmax(0, 1fr));", styles)
        self.assertIn(
            '"type type search search year year operation operation value value"',
            styles,
        )

    def test_editor_sidebar_is_wider_without_pushing_main_pane_offscreen(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        self.assertIn("--scenario-sidebar-width: 340px", styles)
        self.assertIn("max-width: 100%", styles)
        self.assertIn("overflow: hidden", styles)
        self.assertIn("Math.max(320", source)

    def test_queue_drag_does_not_late_capture_pointer_in_webview(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        queue_drag = source[source.index("function enableQueueDragging"):source.index("function consoleBatchJobs")]
        self.assertNotIn("setPointerCapture", queue_drag)

    def test_editor_distinguishes_saved_baseline_changes_from_unsaved_preview(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        self.assertIn("editorBaselineRows", source)
        self.assertIn("baselineEditorFileUrl", source)
        self.assertIn('saved ? "saved-change-cell"', source)
        self.assertIn('unsaved ? "changed-cell"', source)
        self.assertIn("Saved scenario change from baseline", source)
        self.assertIn("Saved change from baseline", markup)
        self.assertIn("Unsaved preview", markup)
        self.assertIn(".editor-table td.saved-change-cell", styles)

    def test_new_batch_visit_resets_scenario_scoped_draft(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        self.assertIn(
            "if (!batchSessionMatches(scenario.id)) resetBatchDraft(scenario.id);",
            source,
        )
        self.assertIn("function batchSessionMatches(", source)
        self.assertIn("function clearBatchDraftState(", source)
        self.assertIn(
            'const shouldResetDraft = state.editorMode !== "scenario" || !batchSessionMatches(scenarioId);',
            source,
        )
        self.assertIn(
            'clearBatchDraftState("");',
            source,
        )
        self.assertIn(
            'state.editorVariationId = scenario.id; state.editorMode = "file"; clearEditorFile();',
            source,
        )
        self.assertIn('fileSignature !== currentFileSignature', source)
        self.assertIn('sessionOwner !== state.batchSessionOwner', source)
        self.assertIn('input.checked = state.batchSelectedFiles.has(input.dataset.batchFile);', source)
        self.assertIn('box.checked = state.batchSelectedColumns.get(box.dataset.batchColumnFile)?.has(box.dataset.batchColumn) || false;', source)
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        self.assertIn(
            ".batch-location-type, .batch-location-search, .batch-year, .batch-operation, .batch-value { grid-column: span 2; }",
            styles,
        )
        self.assertIn('.batch-editor-grid > label { min-width: 0; }', styles)
        self.assertIn('height: 40px; min-height: 40px;', styles)
        self.assertIn('resetBatchDraft(state.editorVariationId);', source)
        self.assertIn('calculatedValue(next, "batch", csvPayload, column)', source)
        self.assertIn('const priorYear = $("batchYear").value;', source)
        self.assertIn('<option value="">Choose operation</option>', markup)

    def test_batch_editor_has_one_guarded_scenario_scoped_implementation(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        self.assertEqual(source.count("function renderBatchFiles("), 1)
        self.assertEqual(source.count("async function renderBatchColumns("), 1)
        self.assertIn("function resetBatchDraft(", source)
        self.assertIn("requestId !== state.batchColumnsRequestId", source)
        self.assertIn("state.batchSelectedFiles", source)
        self.assertIn("state.batchSelectedColumns", source)

    def test_dependency_canvas_and_runtime_overflow_controls_are_present(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        for control in ("dependencyZoomOut", "dependencyZoomIn", "dependencyZoomActual", "dependencyZoomFit", "dependencySearch", "dependencyExportSvg", "dependencyExportPdf", "dependencyExportHtml"):
            self.assertIn(f'id="{control}"', markup)
        for control in ("dependencyFocusContext", "dependencyBreadcrumb", "dependencyScopeToggle"):
            self.assertIn(f'id="{control}"', markup)
        self.assertIn(".dependency-minimap", styles)
        self.assertIn("[data-dependency-scope]", source)
        self.assertIn("[data-dependency-view]", source)
        self.assertIn("dependencyNavigation", source)
        self.assertIn("graph.focusView?.metrics", source)
        self.assertIn("originId", source)
        self.assertIn("scope", source)
        self.assertIn("Export SVG", markup)
        self.assertIn("Export PDF", markup)
        self.assertIn("Export HTML", markup)
        self.assertLess(markup.index("dependency-search-row"), markup.index("dependency-zoom-row"))
        self.assertLess(markup.index("dependency-zoom-row"), markup.index("dependency-export-row"))
        self.assertIn(".dependency-zoom-row", styles)
        self.assertIn("dependency-export-row", markup)
        self.assertIn("editable SVG vector diagram", markup)
        self.assertIn("paginated PDF for printing or sharing", markup)
        self.assertIn("standalone HTML page", markup)
        self.assertIn('invoke("save_dependency_export"', source)
        self.assertNotIn('dependencyExportSvg").href', source)
        self.assertIn('saveDependencyExport("html")', source)
        self.assertIn("dependencyTemplateControl", markup)
        self.assertIn('VisionEval module catalog (built in)', source)
        self.assertIn("const hideTemplate = false", source)
        self.assertIn("template-hidden", source)
        self.assertLess(markup.index('id="dependencyMetrics"'), markup.index('class="panel dependency-toolbar"'))
        self.assertLess(markup.index('class="panel dependency-toolbar"'), markup.index('class="panel dependency-panel"'))
        self.assertIn("How produced traces upstream", markup)
        self.assertIn(".runtime-digest", styles)
        self.assertIn("overflow-x: hidden", styles)

    def test_run_queue_stop_all_controls_and_context_menu_are_present(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        rust = (ROOT / "desktop" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        self.assertIn("Choose a project to select baseline and scenarios.", markup)
        self.assertIn("run-empty-state", source)
        self.assertIn(".run-empty-state", styles)
        self.assertIn(".run-empty-state { display: none; }", styles)
        self.assertIn("openQueuedJobMenu", source)
        self.assertIn("No completed results are affected", source)
        self.assertIn("/api/runs/queue/remove", source)
        self.assertIn("Drag to reorder", source)
        self.assertIn("queue-drag-cue", source)
        self.assertNotIn('draggable="true"', source)
        self.assertIn('addEventListener("pointerdown"', source)
        self.assertIn('addEventListener("pointermove"', source)
        self.assertIn("queue-insertion-line", source)
        self.assertIn(".queue-insertion-line", styles)
        self.assertNotIn("data-queue-up", source)
        self.assertNotIn("data-queue-down", source)
        self.assertIn("Stop All Runs", source)
        self.assertIn("stopAllPending", source)
        self.assertIn("Stops only the selected active run", source)
        self.assertIn("Stops every active run", source)
        self.assertIn("followActiveConsoleJob", source)
        self.assertIn("consoleAutoFollowJob", source)
        self.assertIn("consoleManualSelection", source)
        self.assertIn("auto-following", styles)
        self.assertIn("/api/runs/stop-all", source)
        self.assertIn("stop-all-runs", source)
        self.assertIn("hasRunnableJobs", source)
        self.assertIn("stop-all-runs", rust)
        self.assertIn("has_runnable_jobs", rust)

    def test_windows_native_runtime_forces_queued_runs(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        rust = (ROOT / "desktop" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        self.assertIn('id="parallelRunMode"', markup)
        self.assertIn('id="maxConcurrentRuns"', markup)
        self.assertIn('$("parallelRunMode").hidden=native', source)
        self.assertIn('$("defaultRunMode").disabled=native', source)
        self.assertIn('$("maxConcurrentRuns").value=native?"1":"2"', source)
        self.assertIn('runtime.adapter==="native"', source)
        self.assertIn('id="settingsVeHome"', markup)
        self.assertIn('id="settingsRscript"', markup)
        self.assertNotIn("ve-40-rc6-planrva-amd64", markup)
        self.assertIn('cfg!(target_os = "windows")', rust)
        self.assertIn('"native"', rust)
        self.assertIn('"docker"', rust)
        self.assertIn('profile.adapter == "native"', rust)
        self.assertIn("Stop All Runs", source)
        self.assertIn("Stopping All…", source)
        self.assertIn("stopAllPending", source)
        self.assertIn("Stops only the selected active run", source)
        self.assertIn("Stops every active run", source)
        self.assertIn("/api/runs/stop-all", source)
        self.assertIn("stop-all-runs", source)
        self.assertIn("hasRunnableJobs", source)
        self.assertIn("stop-all-runs", rust)
        self.assertIn("has_runnable_jobs", rust)

    def test_generic_surfaces_do_not_use_optional_package_branding(self):
        script = ROOT / "packaging" / "check_generic_identity.py"
        spec = importlib.util.spec_from_file_location("check_generic_identity", script)
        module = importlib.util.module_from_spec(spec)
        self.assertIsNotNone(spec.loader)
        spec.loader.exec_module(module)
        self.assertEqual(module.violations(), [])

    def test_editor_sidebar_resizes_and_review_scenarios_collapse(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        self.assertNotIn('id="toggleScenarioSidebar"', markup)
        self.assertIn('id="scenarioSidebarResizer"', markup)
        self.assertIn('role="separator"', markup)
        self.assertIn("setScenarioSidebarWidth", source)
        self.assertIn("visioneval-scenario-sidebar-width", source)
        self.assertIn(".scenario-sidebar-resizer", styles)
        self.assertNotIn("sidebar-collapsed", styles)
        self.assertIn('<details class="review-scenario"', source)
        self.assertIn('<summary>', source)
        self.assertIn("reviewExpandedScenarioIds", source)
        self.assertIn(".review-scenario > summary", styles)
        self.assertIn(".change-editor-grid > label > input", styles)
        self.assertIn("height: 40px; min-height: 40px;", styles)

    def test_header_settings_gear_opens_settings(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        self.assertIn('id="settingsGear"', markup)
        self.assertIn('aria-label="Open settings"', markup)
        self.assertLess(markup.index('id="themeToggle"'), markup.index('id="settingsGear"'))
        self.assertIn('$("settingsGear").addEventListener("click",()=>openSettings());', source)

    def test_explore_library_copy_and_field_labels_are_clear(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        backend = (ROOT / "backend" / "workbench" / "explore.py").read_text(encoding="utf-8")
        self.assertIn(
            "Input explanations were developed for a Virginia dataset. They can still help interpret other VisionEval input files, but locally customized inputs may differ.",
            markup,
        )
        self.assertIn("Fields in this file", source)
        self.assertNotIn("Variables in this file", source)
        self.assertIn("Description not available in the packaged guide.", backend)
        self.assertIn(".explore-toolbar input, .explore-toolbar select, .dependency-toolbar select", styles)
        self.assertIn(".dependency-toolbar button", styles)

    def test_input_explanations_replace_unit_model_control(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        self.assertIn("Input explanations", markup)
        self.assertIn('id="exploreExplanations"', markup)
        self.assertNotIn("Unit model", markup)
        self.assertNotIn('id="exploreTemplate"', markup)
        self.assertNotIn('id="exploreLevel"', markup)
        self.assertIn("explanationPackageId", source)
        self.assertNotIn("exploreLevel", source)

    def test_settings_assets_use_installable_package_language(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        self.assertIn("Choose ZIP", markup)
        self.assertIn("Choose extracted folder", markup)
        self.assertIn('id="settingsInstallPackage"', markup)
        self.assertIn('id="defaultInputExplanations"', markup)
        self.assertIn('id="installedAssetGroups"', markup)
        self.assertIn("Import an InputLibrary", markup)
        self.assertNotIn('id="settingsImportTemplate"', markup)
        self.assertNotIn('id="templateImportForm"', markup)
        self.assertIn('id="settingsNumbers"', markup)
        self.assertIn('data-settings-page="settingsAbout"', markup)
        self.assertIn('id="settingsAbout"', markup)
        self.assertIn('id="settingsAboutVersion"', markup)
        self.assertIn('id="aboutDialog"', markup)
        self.assertIn('id="aboutDialogVersion"', markup)
        self.assertIn("function openAboutDialog()", source)
        self.assertIn("if(action==='about')return openAboutDialog();", source)
        self.assertIn('class="settings-section settings-control-group"', markup)
        self.assertNotIn('<option value="parallel">', markup)
        for control in ("precisionDefault", "precisionSingleFile", "precisionBatch", "precisionOutput", "precisionPercentage"):
            self.assertIn(f'id="{control}"', markup)
        self.assertIn("numericPrecision", source)
        self.assertIn('calculatedValue(next, "singleFile", state.csv, column)', source)
        self.assertIn("Verify runtime", markup)
        self.assertNotIn("Verify / Repair", markup)
        self.assertNotIn("after publication", markup)
        self.assertIn("Input explanations", source)
        self.assertIn('picker = "choose_package"', source)
        self.assertIn("invoke(picker)", source)
        self.assertIn('"choose_package_folder"', source)
        self.assertIn("/api/packages/install", source)
        self.assertNotIn("Bundled PlanRVA MM example", markup)
        self.assertNotIn("installBundledPlanrva", source)

    def test_windows_desktop_registers_single_instance_before_other_plugins(self):
        rust = (ROOT / "desktop" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        single_instance = rust.index("tauri_plugin_single_instance::init")
        dialog = rust.index("tauri_plugin_dialog::init")
        notification = rust.index("tauri_plugin_notification::init")
        self.assertLess(single_instance, dialog)
        self.assertLess(single_instance, notification)
        self.assertIn('"about",\n                "About VisionEval Workbench"', rust)

    def test_handoff_settings_and_custom_region_contracts(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        rust = (ROOT / "desktop" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        self.assertIn('"light".into()', rust)
        self.assertIn('storedTheme || "light"', source)
        self.assertIn('id="settingsNotice"', markup)
        self.assertIn('id="settingsRefreshWorkbench"', markup)
        save_handler = source[source.index('$("settingsForm").addEventListener("submit"'):]
        self.assertNotIn('$("settingsDialog").close()', save_handler)
        self.assertIn("switchSettingsPage(activePage)", save_handler)
        self.assertIn('message:"Settings saved and applied."', source)
        self.assertIn("settingsSaveOutcome(before,requested,native)", save_handler)
        self.assertIn('invoke("restart_backend")', source)
        self.assertIn("Refresh is unavailable while runs are active or waiting.", source)
        self.assertIn('role", type === "error" ? "alert" : "status"', source)
        self.assertIn('nonterminal_job_count(Path::new(&config.workspace_root)) > 0', rust)
        self.assertNotIn("macOS Apple silicon Docker", markup)
        self.assertIn('id="parallelRunMode" class="mode-option" hidden', markup)
        self.assertIn('const preferred=native?"queued"', source)
        self.assertNotIn("showSettingsPage(", source)
        self.assertIn("settingsDialog?.open", source)
        self.assertIn("regionBuilderOfficialIdentity", source)
        self.assertIn("regionBuilderCustomIdentity", source)
        self.assertIn("customRegionIdentityValid", source)
        self.assertIn('selected.size === 0 || !customRegionIdentityValid()', source)
        self.assertIn("sceneKey", source)
        self.assertIn("scheduleRegionGeographyMapRender", source)
        self.assertIn("pointer-events:none", styles)

    def test_workspace_setup_and_recent_workspace_management_are_explicit(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        setup = (ROOT / "desktop" / "src" / "index.html").read_text(encoding="utf-8")
        rust = (ROOT / "desktop" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        permissions = (ROOT / "desktop" / "src-tauri" / "permissions" / "workbench.toml").read_text(encoding="utf-8")
        self.assertNotIn('class="steps"', setup)
        self.assertIn("Change location…", setup)
        self.assertIn("Open existing workspace…", setup)
        self.assertIn('invoke("create_workspace"', setup)
        self.assertIn('invoke("choose_workspace_destination"', setup)
        self.assertIn('id="settingsOtherWorkspaces"', markup)
        self.assertIn("Open another workspace…", markup)
        self.assertIn("Move workspace…", markup)
        self.assertIn('invoke("forget_workspace"', source)
        self.assertIn('invoke("trash_workspace"', source)
        self.assertIn(".workspace-recent-row", styles)
        for command in ("create_workspace", "choose_workspace_destination", "forget_workspace", "trash_workspace"):
            self.assertIn(f'"{command}"', permissions)
            self.assertIn(command, rust)

    def test_compare_uses_read_only_results_discovery_and_native_exports(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        rust = (ROOT / "desktop" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        for control in ("exportAllChangedCsv", "exportAllChangedWorkbook", "exportSelectedChangedCsv", "exportSelectedChangedWorkbook", "exportCurrentWorkbook", "exportFullVariablesZip", "exportFullVariablesWorkbook", "exportGeoControls", "fullExportVariableList", "scanScopeAll", "scanScopeSelected", "findChangedOutputs", "compareViewGeoControls", "compareGeoControls", "dashboardGeoControls", "dashboardDisplayMode", "dashboardHideZero", "exportDashboardCsv", "exportDashboardWorkbook"):
            self.assertIn(f'id="{control}"', markup)
        self.assertNotIn('id="datastoreImportForm"', markup)
        self.assertNotIn('id="showHiddenDatastores"', markup)
        self.assertNotIn("Data-path profiler", markup)
        self.assertNotIn("/api/datastores/import", source)
        self.assertNotIn("/api/datastores/hide", source)
        self.assertNotIn("/api/datastores/remove", source)
        self.assertNotIn("/api/comparison/profile-data-paths", source)
        self.assertIn("Legacy · read only", source)
        self.assertIn("Previously registered", source)
        self.assertIn("Discover changed outputs", markup)
        self.assertIn("Export data", markup)
        self.assertIn("All Locations Changed Outputs", markup)
        self.assertIn("Selected Locations Changed Outputs", markup)
        self.assertIn("Full Variable Data", markup)
        self.assertIn("hideZero:String(settings.hideZero)", source)
        self.assertNotIn("Changed Rows in Current View", markup)
        self.assertNotIn("Reference Values", markup)
        self.assertNotIn("dashboardUseLocation", markup)
        self.assertIn("location-selector-trigger", styles)
        self.assertIn("dashboardDisplayRows", source)
        self.assertIn('state.compareLocationDirty=Boolean(state.lastComparison)', source)
        self.assertIn("scanFilterValues", source)
        self.assertIn('comparisonToken:state.lastComparison.comparisonToken', source)
        self.assertIn('marker=direction==="asc"?"↑":direction==="desc"?"↓":"---"', source)
        self.assertIn('aria-sort="${aria}"', source)
        self.assertIn("iqrComparison", source)
        self.assertIn("aggregate-average-change", source)
        self.assertIn("Average change", source)
        self.assertIn("change.measures?.mean?.percentChange", source)
        self.assertIn('phase==="preparing_cache"', source)
        self.assertIn("Preparing comparison cache", source)
        self.assertIn('id="notificationSuccessThreshold"', markup)
        self.assertIn("notificationSuccessThresholdSeconds", source)
        self.assertIn('force:true', source)
        self.assertIn("matched numeric rows", source)
        self.assertIn('id="compareResultsPanel"', markup)
        self.assertIn('id="comparisonResults"', markup)
        self.assertNotIn('id="comparisonSummary"', markup)
        self.assertIn('compareResultMode: "comparison"', source)
        self.assertIn('activateCompareResultMode("changedOutputs")', source)
        self.assertNotIn('header("Changed rows","changed")', source)
        self.assertNotIn('header("Total rows","total")', source)
        self.assertIn('class="iqr-values"', source)
        self.assertIn('id="toggleDashboardVariables"', markup)
        self.assertIn('id="dashboardVariableSearch"', markup)
        self.assertIn("setDashboardVariablesExpanded(false)", source)
        self.assertIn("updateDashboardVariableVisibility", source)
        self.assertIn(".dashboard-view-controls.has-display-value", styles)
        self.assertIn("comparisonValuesDiffer", source)
        self.assertIn('tr:not(.changed) td', styles)
        self.assertIn("At least ± threshold", markup)
        self.assertIn('metric("Not charted"', source)
        self.assertIn("/api/comparison/exports/start", source)
        self.assertIn('invoke("save_backend_export"', source)
        self.assertIn(".comparison-controls input, .comparison-controls select, .comparison-controls > button { height: 40px; }", styles)
        self.assertIn("user-select: none", styles)
        for item in ("export-dependency-svg", "export-current-csv", "export-all-changed-xlsx", "export-selected-changed", "export-full-variables", "export-dashboard-pdf", "export-dashboard-csv", "export-dashboard-xlsx"):
            self.assertIn(item, rust)
        for control in ("mapReference", "mapComparison", "mapYear", "mapTable", "mapVariable", "mapGeography", "mapAggregation", "generateMap", "mapMetric", "comparisonMapCanvas", "comparisonMapValueLabels", "toggleMapExport", "mapExportMenu", "exportMapPdf", "exportMapPng", "exportMapSvg", "exportMapCsv", "exportMapWorkbook"):
            self.assertIn(f'id="{control}"', markup)
        self.assertNotIn('id="comparisonMapRegion"', markup)
        self.assertIn('id="fitComparisonMap"', markup)
        self.assertIn('>Fit project<', markup)
        self.assertIn('comparison-map-detail-cards', source)
        self.assertIn('colors clipped at the 95th percentile', source)
        self.assertIn('comparison-map-scale-axis', source)
        self.assertIn('Above +${percentage(scale.limit)}% scale cap', source)
        self.assertLess(source.index('comparison-map-gradient diverging'), source.index('comparison-map-legend-keys'))
        for control in ("hideRunHistory", "showRunHistory", "compareMode", "appRecovery", "projectAssetIdentity"):
            self.assertIn(f'id="{control}"', markup)
        self.assertIn('data-subpage="mapData"', markup)
        self.assertIn("/api/comparison/map-options", source)
        self.assertIn("/api/comparison/operations/start", source)
        self.assertIn("full.width / 256", source)
        self.assertIn('table in {"Vehicle", "Worker"}', (ROOT / "backend" / "workbench" / "comparison.py").read_text(encoding="utf-8"))
        self.assertIn('f"{table}.HhId -> Household.HhId -> Household.Bzone"', (ROOT / "backend" / "workbench" / "comparison.py").read_text(encoding="utf-8"))
        self.assertIn("setComparisonMapExportOpen(false)", source)
        self.assertIn("comparisonMapSpatialIndex", source)
        self.assertIn("setApplicationZoom", source)
        self.assertIn('aggregation not in {"mean", "sum", "count"}', (ROOT / "backend" / "workbench" / "comparison.py").read_text(encoding="utf-8"))
        for item in ("export-map-pdf", "export-map-png", "export-map-svg", "export-map-csv", "export-map-xlsx", "save_visual_export", "zoom-in", "zoom-out", "actual-size", "map-zoom-in", "map-fit-mpo", "map-virginia", "set_app_zoom"):
            self.assertIn(item, rust)
        for removed in ("export-changed-xlsx", "export-scan-xlsx"):
            self.assertNotIn(removed, rust)
        self.assertNotIn("export-reference-csv", rust)

    def test_explicit_docker_start_and_safe_quit_commands_are_allowed(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        permissions = (ROOT / "desktop" / "src-tauri" / "permissions" / "workbench.toml").read_text(encoding="utf-8")
        rust = (ROOT / "desktop" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        for control in ("startDockerDesktop", "onboardingStartDocker", "settingsStartDocker"):
            self.assertIn(f'id="{control}"', markup)
        self.assertIn('invoke("start_docker_desktop")', source)
        self.assertIn('invoke("complete_quit")', source)
        self.assertIn('"start_docker_desktop"', permissions)
        self.assertIn('"complete_quit"', permissions)
        self.assertIn('"save_dependency_export"', permissions)
        self.assertIn("fn start_docker_desktop()", rust)
        self.assertIn('"show-workspace-in-finder"', rust)
        self.assertIn('invoke("reveal_workspace_location"', source)
        self.assertIn("VE dependency {stamp}.{format}", rust)
        self.assertIn("async fn save_dependency_export(", rust)
        self.assertIn(".download_dir()", rust)
        self.assertNotIn("start_docker_desktop_if_requested", rust)

    def test_runtime_is_pinned_to_official_rc6_with_unofficial_workbench_patch(self):
        dockerfile = (ROOT / "runtime" / "Dockerfile").read_text(encoding="utf-8")
        cli = (ROOT / "runtime" / "scripts" / "ve-cli.R").read_text(encoding="utf-8")
        self.assertIn("VISIONEVAL_REF=VE-40-RC6", dockerfile)
        self.assertIn("f7ef3389b5626daeba6c86eeda9d172a0f8cccc2", dockerfile)
        self.assertIn('com.visioneval.upstream.release="VE-40-RC6"', dockerfile)
        self.assertIn('com.visioneval.workbench.compatibility-patch-status="unofficial"', dockerfile)
        self.assertIn("apply-household-id-prediction-ordering-patch.R", dockerfile)
        self.assertIn("household-ID prediction-ordering compatibility patch", dockerfile)
        self.assertNotIn("PlanRVA", dockerfile)
        self.assertNotIn("PlanRVA", cli)
        self.assertIn('verify-upstream-release', cli)
        self.assertIn('verify-alignment-patch', cli)
        self.assertFalse((ROOT / "runtime" / "patches" / "AlignPredictions.R").exists())
        self.assertFalse((ROOT / "runtime" / "scripts" / "apply-household-alignment-patch.R").exists())

    def test_stale_workspace_asset_defaults_fall_back_to_installed_assets(self):
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        self.assertIn("libraryIds.has(preferredLibrary)", source)
        self.assertIn("libraries.some((item) => item.id === preferredLibrary)", source)
        self.assertIn("templates.some((item) => item.id === preferredTemplate)", source)

    def test_windows_runtime_setup_is_version_independent_and_platform_aware(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        runtime = (ROOT / "backend" / "workbench" / "runtime.py").read_text(encoding="utf-8")
        cli = (ROOT / "runtime" / "scripts" / "ve-cli-native.R").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        for control in ("onboardingVeRuntime", "settingsVeRuntime", "settingsVeHome", "settingsRscript"):
            self.assertIn(f'id="{control}"', markup)
        self.assertIn('/api/runtime/discover', source)
        self.assertIn('veRuntimePath', source)
        self.assertIn('notificationsPlatformLabel', markup)
        self.assertIn('Windows notifications', source)
        self.assertIn('WORKBENCH_RUNTIME_INFO', cli)
        self.assertIn('checkModuleExists', cli)
        self.assertIn('verify-model', cli)
        self.assertNotIn('.tools\\VisionEval', runtime)
        self.assertIn('overflow-x: hidden', styles)
        self.assertIn('@media (max-width: 1100px)', styles)

    def test_settings_dialog_is_resizable_persistent_and_viewport_safe(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        self.assertIn('id="settingsDialogResizer"', markup)
        self.assertIn('aria-label="Resize Settings window"', markup)
        self.assertIn('SETTINGS_DIALOG_SIZE_KEY = "visioneval-settings-dialog-size-v1"', source)
        self.assertIn('SETTINGS_DIALOG_DEFAULT_SIZE = Object.freeze({width:880,height:720})', source)
        self.assertIn('TASKBAR_SAFE_MARGIN = Object.freeze({horizontal:20,top:24,bottom:144})', source)
        self.assertIn('minWidth:Math.min(520,maxWidth)', source)
        self.assertIn('minHeight:Math.min(420,maxHeight)', source)
        self.assertIn('width:viewport?.width', source)
        self.assertIn('viewport?.offsetLeft', source)
        self.assertIn('viewport?.offsetTop', source)
        self.assertIn('dialog.style.left=', source)
        self.assertIn('dialog.style.top=', source)
        self.assertIn('applySettingsDialogPreferredSize();', source)
        self.assertIn('lockSettingsBackgroundScroll()', source)
        self.assertIn('unlockSettingsBackgroundScroll()', source)
        self.assertIn('if(!$("settingsDialog").open)', source)
        self.assertIn('event.key==="Home"', source)
        self.assertIn('["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"]', source)
        self.assertIn('.settings-dialog-resizer', styles)
        self.assertIn('cursor:nwse-resize', styles)
        self.assertIn('#settingsDialog { position:fixed', styles)
        self.assertIn('html.settings-dialog-open, body.settings-dialog-open', styles)
        self.assertIn('width:34px; height:34px', styles)

    def test_region_builder_hides_statewide_and_matches_macos_map_label_defaults(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        labels = (ROOT / "public" / "polygon-labels.js").read_text(encoding="utf-8")
        self.assertIn('item.regionType !== "statewide"', source)
        self.assertIn('id="regionMapNameLabels" type="checkbox" checked', markup)
        self.assertIn('id="regionMapIdLabels" type="checkbox"> Zone ID labels', markup)
        self.assertIn("Selected MPO locality names", markup)
        self.assertIn("region?.azoneFips", source)
        self.assertIn("zoom >= 40", source)
        self.assertIn("zoom >= 1.75", source)
        self.assertIn('id="comparisonMapIdLabels" type="checkbox" checked', markup)
        for control in ("comparisonMap2d", "comparisonMap3d", "comparisonMap3dHeight", "comparisonMap3dCanvas", "resetComparisonMapBearing"):
            self.assertIn(f'id="{control}"', markup)
        for control in ("regionGeographyMap", "clearRegionGeography", "selectVisibleAzones"):
            self.assertIn(f'id="{control}"', markup)
        self.assertIn("regionMapInteriorLabel", source)
        self.assertIn("regionMapSignedDistance", source)
        self.assertIn('`url(#${clipId})`', labels)
        self.assertIn("initializeComparisonMap3dCapability", source)
        self.assertIn("renderComparisonMap3dBars", source)
        self.assertIn("Build your own region", markup)
        self.assertIn("Click Azones or Bzones", markup)
        self.assertIn("operationKind:'change-density'", source)
        self.assertIn('vendor/maplibre/maplibre-gl.css', markup)
        self.assertIn('scene.localityNames.get(String(id))', source)

    def test_custom_region_apply_preview_workflow_contract(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        self.assertIn('id="customGeographyHeading"', markup)
        for removed in ("regionGeographyMpo", "replaceRegionWithMpo", "addRegionMpo", "subtractRegionMpo"):
            self.assertNotIn(f'id="{removed}"', markup)
            self.assertNotIn(f'$("{removed}")', source)
        self.assertIn('id="customRegionMpoLayer"', markup)
        order = ["regionGeographySearch", "regionDisplayControls", "regionGeographyMap", "regionGeographyAzones"]
        self.assertEqual(order, sorted(order, key=lambda item: markup.index(f'id="{item}"')))
        self.assertIn('class="region-geography-map-overlay"', markup)
        self.assertNotIn('id="regionNavigationControls"', markup)
        self.assertIn('class="region-geography-footer"', markup)
        self.assertIn("position: sticky", styles)
        self.assertIn('$("applyRegionGeography").disabled = selected.size === 0', source)
        self.assertIn("new Set(state.regionBuilderDraftBzones)", source)
        self.assertIn("regionBuilderDraftInitialized", source)
        self.assertIn('switchCreateSubpage("createDevelop", false)', source)
        self.assertGreaterEqual(source.count("previewRegionBuild("), 3)
        self.assertIn("regionBuilderPreviewError", source)
        self.assertIn("Your geography selection is preserved", source)

    def test_custom_region_independent_label_controls(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        self.assertIn('id="customRegionAzoneLabels" type="checkbox" checked', markup)
        self.assertIn('id="customRegionAzoneIdLabels" type="checkbox"', markup)
        self.assertIn('id="customRegionBzoneLabels" type="checkbox"', markup)
        self.assertIn('showAzoneNames && showAzoneIds', source)
        self.assertIn('[[name, id]', source)
        self.assertIn('"custom-region-azone-id-label"', source)
        self.assertIn('group.toggleAttribute("hidden", !visible)', source)
        self.assertIn('group.style.pointerEvents = visible ? "" : "none"', source)
        self.assertNotIn('canvas.querySelector("[data-custom-region-azones]").hidden', source)
        self.assertIn('if (showAzoneNames || showAzoneIds)', source)
        self.assertIn('if ($("customRegionBzoneLabels")?.checked)', source)
        self.assertNotIn('(showAzoneNames || showAzoneIds) && $("customRegionAzoneLayer")?.checked', source)
        self.assertNotIn('$("customRegionBzoneLabels")?.checked && $("customRegionBzoneLayer")?.checked', source)
        self.assertNotIn("regionGeographyMpoBzones", source)
        self.assertNotIn("removed from official", source)

    def test_polygon_extrusions_and_palette_cards_contract(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        smoke = (ROOT / "public" / "map3d-smoke.js").read_text(encoding="utf-8")
        self.assertIn("geometry:feature.geometry", source)
        self.assertNotIn("point.x-side", source)
        self.assertIn("directionVisible&&['increase','decrease'].includes(direction)?ratio*12000:0", source)
        self.assertIn("project:valueFeatures", source)
        self.assertIn("polygonExtrusion", smoke)
        self.assertIn("smoke-project-polygon", smoke)
        self.assertIn('class="muted palette-intro"', markup)
        self.assertIn("palette-color-control", source)
        self.assertIn("['decrease','neutral','increase']", source)
        self.assertIn("palette-color-copy", source)
        self.assertIn("linear-gradient", styles)
        self.assertIn("Choose color…", source)
        self.assertIn('aria-label="Choose ${title.toLowerCase()} color', source)
        self.assertIn(".palette-card-footer", styles)
        self.assertIn("container-name:palette-settings", styles)
        self.assertIn("container-type:inline-size", styles)
        self.assertIn(".palette-grid { display:grid; grid-template-columns:minmax(0,1fr)", styles)
        self.assertIn("@container palette-settings (min-width:1080px)", styles)
        self.assertIn("grid-template-columns:repeat(2,minmax(0,1fr))", styles)
        self.assertIn("@container palette-settings (max-width:640px)", styles)
        self.assertIn("overflow-x:hidden; overflow-y:auto", styles)
        self.assertIn("overflow-wrap:anywhere", styles)
        self.assertNotIn(".palette-card.palette-overridden { opacity", styles)

    def test_viewport_master_palette_and_advanced_3d_contract(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        rust = (ROOT / "desktop" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        self.assertIn("--workbench-viewport-height", styles)
        self.assertIn("window.visualViewport?.height", source)
        self.assertIn("--workbench-page-bottom-gutter", styles)
        self.assertIn("max-height: calc(var(--workbench-viewport-height)", styles)
        self.assertIn("settings-dialog-body", markup)
        self.assertIn("dialog-fixed-footer", markup)
        self.assertIn("#onboardingDialog { position:fixed", styles)
        self.assertIn("#onboardingForm > .dialog-fixed-footer", styles)
        self.assertIn("TASKBAR_SAFE_MARGIN", source)
        self.assertIn("applyOnboardingDialogBounds();", source)
        self.assertIn("Master palette", source)
        self.assertIn("useMasterComparisonPalette", source)
        self.assertIn("master_comparison_palette", rust)
        for control in ("comparisonMapProjectOnly", "comparisonMap3dElevationDirection", "comparisonMap3dAdvanced"):
            self.assertIn(f'id="{control}"', markup)
        self.assertNotIn("comparisonMap3dSmoothing", source)
        self.assertIn("WorkbenchExtrusionBorders", source)
        self.assertIn("NavigationControl", source)
        self.assertIn("preserveDrawingBuffer:true", source)
        self.assertNotIn("state.comparisonMap3d?.remove()", source)
        self.assertIn("canvas.toDataURL('image/png')", source)
        self.assertIn("grid-template-rows: auto auto auto minmax(520px, 68vh) auto auto", styles)
        self.assertIn("comparisonMap3dDefaultCamera", source)
        self.assertIn("comparisonMapOptionsInflight", source)
        self.assertIn("function comparisonMap3dVirginiaBounds", source)
        self.assertIn("scene.azones?.length?scene.azones:scene.bzones?.length?scene.bzones:scene.mpos", source)
        self.assertNotIn("state.comparisonMap3dScene?.context", source)

    def test_taskbar_safe_setup_export_and_signed_3d_contract(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        setup = (ROOT / "desktop" / "src" / "index.html").read_text(encoding="utf-8")
        borders = (ROOT / "public" / "extrusion-borders.js").read_text(encoding="utf-8")
        self.assertIn("window.visualViewport?.height", setup)
        self.assertIn("--workbench-page-bottom-gutter: 160px", styles)
        self.assertIn("TASKBAR_SAFE_MARGIN", source)
        self.assertIn('querySelectorAll(".taskbar-safe-dialog:not(#onboardingDialog):not(#settingsDialog)")', source)
        self.assertIn("container: comparison-map / inline-size", styles)
        self.assertIn("@container comparison-map (max-width: 1180px)", styles)
        self.assertIn(".comparison-map-presentation > * { min-width: 0; }", styles)
        self.assertNotIn('<option value="below">', markup)
        self.assertNotIn("zero-plane", source)
        self.assertNotIn("below zero", source.lower())
        self.assertIn("comparisonMap3dElevationDirection", source)
        self.assertIn("function comparisonMapSignedValue", source)
        self.assertIn("▼ Decrease", source)
        self.assertIn("▲ Increase", source)
        self.assertIn("decrease&&index%2===1", borders)

    def test_comparison_selector_context_values_and_elevated_border_contract(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "public" / "styles.css").read_text(encoding="utf-8")
        borders = (ROOT / "public" / "extrusion-borders.js").read_text(encoding="utf-8")
        smoke = (ROOT / "public" / "map3d-smoke.js").read_text(encoding="utf-8")
        self.assertIn('role="radiogroup"', markup)
        self.assertIn('role="radio" aria-checked="true"', markup)
        self.assertIn("comparison-map-mode-slider", markup)
        self.assertIn("comparison-map-mode.is-3d", styles)
        self.assertIn("setAttribute('aria-checked'", source)
        self.assertIn("Azone context", markup)
        self.assertIn("Bzone context", markup)
        self.assertIn("sources:{azones:", source)
        self.assertIn("getSource('azones')", source)
        self.assertIn("getSource('bzones')", source)
        self.assertNotIn("values-line", source)
        self.assertIn("showNames=$('comparisonMapIdLabels').checked,showValues=$('comparisonMapValueLabels').checked", source)
        self.assertIn("__displayValue:displayValue,__heightValue:heightValue", source)
        self.assertIn("__color:color", source)
        self.assertIn("MultiPolygon", borders)
        self.assertIn("elevatedBorders", smoke)
        self.assertIn("borders.renderCount", smoke)
        self.assertIn('src="extrusion-borders.js"', markup)
        self.assertNotIn("earcut", markup.lower())

    def test_develop_mode_switch_and_setup_import_cleanup_contract(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        self.assertIn('id="officialRegionGeographyView"', markup)
        self.assertIn('id="customRegionGeographyView"', markup)
        self.assertIn('id="editCustomRegionGeography"', markup)
        self.assertNotIn('id="setupPanel"', markup)
        self.assertNotIn('id="libraryImportForm"', markup)
        self.assertNotIn('id="templateImportForm"', markup)
        self.assertNotIn('$("customizeRegionGeography").addEventListener("click", openRegionGeographyDialog)', source)
        self.assertIn('$("editCustomRegionGeography").addEventListener("click", openRegionGeographyDialog)', source)

    def test_shared_polygon_label_engine_contract(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        labels = (ROOT / "public" / "polygon-labels.js").read_text(encoding="utf-8")
        self.assertLess(markup.index('src="polygon-labels.js"'), markup.index('src="app.js"'))
        self.assertGreaterEqual(source.count("WorkbenchPolygonLabels.layout"), 2)
        for contract in ("MultiPolygon", "signedDistance", "getBoundingClientRect", "clipPath", "maxLabels", "priority"):
            self.assertIn(contract, labels)
        self.assertIn("shortenLocality", source)
        self.assertIn("devicePixelRatio", source)
        self.assertIn("ResizeObserver", source)

    def test_platform_shortcuts_and_accessibility_are_generated(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        rust = (ROOT / "desktop" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        self.assertIn('data-shortcut="save"', markup)
        self.assertNotIn("<kbd>⌘", markup)
        self.assertIn('other: "Ctrl+S"', source)
        self.assertIn('mac: "⌘S"', source)
        self.assertIn('setAttribute("aria-keyshortcuts"', source)
        self.assertIn("platform: String", rust)

    def test_deterministic_renderer_capability_and_packaging_contract(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        smoke = (ROOT / "public" / "map3d-smoke.js").read_text(encoding="utf-8")
        workflow = (ROOT.parent / ".github" / "workflows" / "release.yml").read_text(encoding="utf-8")
        self.assertIn('vendor/maplibre/maplibre-gl.js', markup)
        self.assertNotIn('type="module" src="map3d.js"', markup)
        self.assertFalse((ROOT / "public" / "map3d.js").exists())
        self.assertFalse((ROOT / "public" / "vendor" / "maplibre" / "maplibre-gl.mjs").exists())
        for capability in ("loading", "ready", "renderer-unavailable", "webgl-unavailable", "initialization-failed"):
            self.assertIn(f"'{capability}'", source)
        initializer = source[source.index("async function initializeComparisonMap3dCapability") :]
        self.assertLess(initializer.index("typeof window.maplibregl?.Map"), initializer.index("probeComparisonMapWebgl()"))
        for phase in ("renderer-assets", "renderer-global", "webgl", "empty-scene", "project-geojson", "fill-extrusion", "elevated-borders"):
            self.assertIn(phase, smoke)
        self.assertIn('src="extrusion-borders.js"', markup)
        self.assertIn("--comparison-map-3d enabled", workflow)
        self.assertIn("--bundles nsis", workflow)
        self.assertNotIn("docker build", workflow.lower())
        self.assertNotIn("workflow_call", workflow.lower())

    def test_desktop_bootstrap_commands_are_allowed_by_tauri_acl(self):
        setup = (ROOT / "desktop" / "src" / "index.html").read_text(encoding="utf-8")
        permission_path = ROOT / "desktop" / "src-tauri" / "permissions" / "workbench.toml"
        with permission_path.open("rb") as handle:
            permissions = tomllib.load(handle)
        allowed = set(permissions["permission"][0]["commands"]["allow"])
        invoked = set(re.findall(r'invoke\("([^"]+)"', setup))
        self.assertTrue(invoked)
        self.assertEqual(set(), invoked - allowed)
        self.assertIn("renderer_smoke_mode", allowed)
        self.assertIn("report_renderer_smoke", allowed)

    def test_frontend_event_bindings_reference_rendered_controls(self):
        markup = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        source = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        rendered_ids = set(re.findall(r'id="([^"]+)"', markup))
        dynamically_rendered_ids = set(re.findall(r'id=\\?"([^"]+)\\?"', source))
        directly_bound_ids = set(re.findall(r'\$\("([^"]+)"\)\.addEventListener', source))
        guarded_ids = set(re.findall(r'if\(\$\("([^"]+)"\)\)\s*\$\("\1"\)\.addEventListener', source))
        self.assertEqual(set(), directly_bound_ids - rendered_ids - dynamically_rendered_ids - guarded_ids)


if __name__ == "__main__":
    unittest.main()
