#!/usr/bin/env python3
"""Create Workbench's deterministic classic MapLibre GL JS 6 browser bundle.

MapLibre 6 publishes split ES modules.  Workbench cannot rely on module-relative
imports inside a frozen sidecar, so this build step scopes the shared module,
embeds the worker, and exposes the public API as ``window.maplibregl``.  The
generated artifact has no runtime JavaScript-module fetches.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


IMPORT_RE = re.compile(
    r'import\{(?P<bindings>.*?)\}from"\./maplibre-gl-shared\.mjs";'
)
EXPORT_RE = re.compile(r"export\{(?P<bindings>.*?)\};\s*(?://# sourceMappingURL=.*)?\s*$")


def binding_pairs(source: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for item in source.split(","):
        names = item.strip().split(" as ")
        if len(names) == 1:
            pairs.append((names[0], names[0]))
        elif len(names) == 2:
            pairs.append((names[0], names[1]))
        else:
            raise ValueError(f"Unexpected module binding: {item!r}")
    return pairs


def shared_factory(shared_source: str) -> str:
    match = EXPORT_RE.search(shared_source)
    if not match:
        raise ValueError("MapLibre shared module export block was not found")
    exports = binding_pairs(match.group("bindings"))
    body = shared_source[: match.start()].rstrip()
    result = ",".join(f"{json.dumps(exported)}:{local}" for local, exported in exports)
    return f"(()=>{{{body};return{{{result}}};}})()"


def inline_module(source: str, shared_expression: str, *, default_export: bool = False) -> tuple[str, str]:
    imported = IMPORT_RE.search(source)
    if not imported:
        raise ValueError("MapLibre module shared import was not found")
    aliases = binding_pairs(imported.group("bindings"))
    destructure = ",".join(f"{json.dumps(exported)}:{local}" for exported, local in aliases)
    body = source[: imported.start()] + source[imported.end() :]
    match = EXPORT_RE.search(body)
    if not match:
        raise ValueError("MapLibre module export block was not found")
    exports = binding_pairs(match.group("bindings"))
    body = body[: match.start()].rstrip()
    body = body.replace("import.meta.url", "(document.currentScript?.src||location.href)")
    if default_export:
        default_local = next((local for local, exported in exports if exported == "default"), None)
        if not default_local:
            raise ValueError("Worker default export was not found")
        result = default_local
    else:
        result = "{" + ",".join(
            f"{json.dumps(exported)}:{local}" for local, exported in exports
        ) + "}"
    return f"const __shared={shared_expression};const{{{destructure}}}=__shared;{body};", result


def build(dist: Path, output: Path) -> None:
    shared = (dist / "maplibre-gl-shared.mjs").read_text(encoding="utf-8")
    main = (dist / "maplibre-gl.mjs").read_text(encoding="utf-8")
    worker = (dist / "maplibre-gl-worker.mjs").read_text(encoding="utf-8")
    shared_expression = shared_factory(shared)
    worker_body, _ = inline_module(worker, shared_expression, default_export=True)
    worker_source = f"(()=>{{'use strict';{worker_body}}})();"
    main_body, main_result = inline_module(main, shared_expression)
    banner = (
        "/* MapLibre GL JS 6.0.0 - classic Workbench browser bundle. "
        "BSD-3-Clause; see LICENSE.txt. Generated by packaging/build_maplibre_classic.py. */\n"
    )
    classic = (
        banner
        + "((global)=>{'use strict';"
        + main_body
        + f"const maplibregl={main_result};"
        + f"const workerSource={json.dumps(worker_source, separators=(',', ':'))};"
        + "const workerUrl=URL.createObjectURL(new Blob([workerSource],{type:'text/javascript'}));"
        + "maplibregl.setWorkerUrl(workerUrl);global.maplibregl=maplibregl;"
        + "global.__WORKBENCH_MAPLIBRE_CLASSIC__={version:maplibregl.getVersion(),workerUrl};"
        + "})(window);\n"
    )
    if "maplibre-gl-shared.mjs" in classic or "import.meta" in classic:
        raise ValueError("Generated classic bundle still contains a module-relative dependency")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(classic, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("dist", type=Path, help="MapLibre 6.0.0 npm dist directory")
    parser.add_argument("output", type=Path, help="Generated classic JavaScript path")
    args = parser.parse_args()
    build(args.dist.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
